### ISSUE TITLE
Update svg-react-transformer depedency to latest version

### ISSUE THREAD

**Issue by mattijsbliek** [mapbox/svg-react-transformer-loader#1]
Would be great if you could get out a new release with the latest svg-react-transformer package :)

**Comment by davidtheclark** [comment]
I believe the release of svg-react-transformer was just a patch so all you should need to do is update your installation.

**Comment by mattijsbliek** [comment]
This package still [requests](https://github.com/mapbox/svg-react-transformer-loader/blob/master/package.json#L33) `0.7.0` of svg-react-transformer, so I’m afraid that won’t work.

**Comment by davidtheclark** [comment]
Oh, oops!

**Comment by davidtheclark** [comment]
Ok, update dependencies in 1.0.1.
